repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--force-single-line-imports"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: 'echo $PWD && coverage run -m pytest --doctest-modules "tests/*" "text_dedup"'
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: pytest-cov
        name: pytest-cov
        stages: [ push ]
        language: system
        entry: "coverage xml -o cobertura.xml"
        types: [ python ]
        pass_filenames: false
        always_run: true
