dataset: oscar-corpus/OSCAR-2109
configs:
  - deduplicated_gl
columns:
  - text
num_proc: 10
num_samples: 400000
embedder:
  name: MinHashEmbedder
  num_perm: 128
  threshold: 0.8
tokenization:
  ngram_size: 6
  level: word
cache_dir: .cache
storage_config:
  type: redis
  redis:
    host: localhost
    port: 6379
# storage_config: null # use null to use dict instead
output: results.json
verbose: true
