dataset: oscar-corpus/OSCAR-2109
configs:
  - deduplicated_gl
columns:
  - text
num_proc: 10
num_samples: 400000
embedder:
  name: SimHashEmbedder
  hamming_distance: 3
  num_blocks: 4
tokenization:
  ngram_size: 2
  level: word
cache_dir: .cache
storage_config:
  type: redis
  redis:
    host: localhost
    port: 6379
# storage_config: null # use null to use dict instead
output: results.json
verbose: true
